import { getCurrentSession } from '@/utils/getSession'
import './globals.css'
import Navbar from '@/components/Navbar'
import Hydrate from '@/components/helpers/Hydrate'
import Footer from '@/components/Footer'
import LoginModal from '@/components/LoginModal'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getCurrentSession()
  return (
    <html lang="en">
     <body >
        <div className='flex flex-col justify-between min-h-screen'>
          
        <Hydrate>
        <LoginModal />
        </Hydrate>

        <Navbar session={session} />
        <div className='min-h-[calc(100vh-84px)] w-full flex justify-center'>
        <div className='min-h-[calc(100vh-84px)]  w-full max-w-[1186px] px-4  flex flex-col items-center justify-start'>
        {children}
        </div>
        </div>
        <Footer />
        </div>    
      </body>  
    </html>
  )
}
